### ISSUE TITLE
How to generate IPNS Hash from *pb.IpnsEntry as according to `ipfs name publish .....`

### ISSUE THREAD

**Issue by postables** [ipfs/go-ipns#4]
When using the command line and publishing an IPNS record using `ipfs name publish.....` you receive back 2 parameters, one is the IPNS hash itself, the other is the value that the IPNS hash resolves to. Currently, I can't seem to figure out a way to pull the IPNS hash off of `*pb.IpnsEntry`

**Comment by postables** [comment]
Interesting 🤔 do you know where I could read up more about how the key and value are generated as according to `ipfs name publish ....`? Or even in depth technical documentation? IPNS seems to be the one part of IPFS which I can't find a lot of example code on.

**Comment by Stebalien** [comment]
Documentation? What is this?

Unfortunately, documentation has always lagged, especially with respect to IPNS. Historically, this has been because js-ipfs doesn't have an IPNS implementation so there was never a need for interoperability. However, now that js-ipfs is implementing IPNS, this will hopefully change.

Currently, IPNS "keys" are just peer IDs. I'd take a look at the code in https://github.com/libp2p/go-libp2p-peer/ to figure out how to generate them.

Really, these should probably be called "key" IDs...

**Comment by postables** [comment]
Oh well, just makes learning it all the more challenging and fun :smile: 
Awesome that will help! thanks for all the super quick response, it has been super helpful in solving these blockers.

**Comment by Stebalien** [comment]
Np. It would be *more* helpful if we actually had documentation... As it is, this is the least I can do.
